name: daily-cron
on:
  schedule:
    - cron: '0 19 * * *'
  # TEST CRON 1
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call update currency price history api route
        run: |
          curl --request POST \
          --url 'https://kantor-galeria.vercel.app/api/cron' \
          --header 'Authorization: Bearer qweqwe123}'
